CREATE TABLE ADMIN.DIM_PRODUCT 
    ( 
     PRODUCTKEY  NUMBER (*,0)  , 
     PRODUCTNAME VARCHAR2 (50) , 
     CATEGORY    VARCHAR2 (20) , 
     SUBCATEGORY VARCHAR2 (20) , 
     BRAND       VARCHAR2 (20) , 
     ISCURRENT   VARCHAR2 (20) , 
     PRODUCTID   NUMBER , 
     SCD_START   DATE , 
     SCD_END     DATE , 
     VERSIONING  NUMBER (*,0) 
    ) 
    TABLESPACE DATA 
    LOGGING 
;

CREATE SEQUENCE product_seq
 START WITH     100
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
