CREATE TABLE ADMIN.FACT_SALES 
    ( 
     SALESID       NUMBER , 
     INVOICENUMBER NUMBER , 
     CUSTOMERKEY   NUMBER , 
     DATEKEY       VARCHAR2 (64) , 
     PRODUCTKEY    NUMBER , 
     SALEPRICE     NUMBER , 
     QUANTITY      NUMBER 
    ) 
    TABLESPACE DATA 
    LOGGING 
;

CREATE SEQUENCE fact_seq
 START WITH     1000
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;

